# Задание №1

In [10]:
import numpy as np
N = int(input('Введите начальное значение диапазона:'))
def new_arrary():
    my_array = np.arange(0,N)
    return np.flip(my_array)
new_arrary()

Введите начальный значение диапазона:10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание №2

In [21]:
import numpy as np
N = int(input('Введите размер диагональной матрицы:'))
def sum_diag():
    my_diag = np.diag(np.flip(np.arange(0, N)))
    print(my_diag)
    return np.sum(np.diag(my_diag))
sum_diag()

Введите знасение матрицы:8
[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]


28

# Задание №3


4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3


In [59]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
print(linalg.solve(a, b))
if np.allclose( np.dot(a, linalg.solve(a, b)), b ):
    print('Решение правльное')


[ 0.46666667  3.84444444 -5.55555556]
Решение правльное


# Задание №4

In [47]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
s = []

def cosine( user_stat, new_user ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    user_stat_Length = np.linalg.norm( user_stat )
    new_user_Length = np.linalg.norm( new_user )
    
    return np.dot( user_stat, new_user ) / ( user_stat_Length * new_user_Length )
def old_user_like_new(s):
    i= np.array(s)
    return 'Новому пользваотелю необходимо рекомендовать товары такие же как купил пользователь ' + str((int(a.argmax())+1))
    

for user_stat in users_stats:
    s.append(cosine(user_stat,next_user_stats))
old_user_like_new(s)

'Новому пользваотелю необходимо рекомендовать товары такие как купил пользователь 8'